Vagrant.configure("2") do |config|

  config.vm.define "areifounS" do |controller|
    controller.vm.box = "generic/alpine312"
    controller.vm.hostname = "areifounS"
    controller.vm.network "private_network", ip: "192.168.56.110"

    controller.vm.synced_folder "./confs", "/vagrant"
    controller.vm.synced_folder "./scripts", "/vagrant"

    controller.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    controller.vm.provision "shell", inline: <<-SHELL
      
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s - \
        --node-ip=192.168.56.110 \
        --advertise-address=192.168.56.110
      
      until kubectl get nodes >/dev/null 2>&1; do
        echo "Waiting for Kubernetes API..."
        sleep 3
      done

      cd / && cd vagrant && sudo chmod +x execute.sh && ./execute.sh
    
    SHELL
  end


end
