Vagrant.configure("2") do |config|

  config.vm.define "areifounS" do |controller|
    controller.vm.box = "ubuntu/focal64"
    controller.vm.hostname = "areifounS"
    controller.vm.network "private_network", ip: "192.168.56.110"

    controller.vm.synced_folder "./apps", "/vagrant"

    controller.vm.provider "virtualbox" do |vb|
      vb.memory = 2024
      vb.cpus = 1
    end

    controller.vm.provision "shell", inline: <<-SHELL
      
      curl -sfL https://get.k3s.io | sh -s - \
        --node-ip=192.168.56.110 \
        --advertise-address=192.168.56.110
      
      cd /vagrant && chmod +x execute.sh && sudo ./execute.sh
    
    SHELL
  end


end
