Vagrant.configure("2") do |config|

  # ----------------------
  # K3s Server VM
  # ----------------------
  config.vm.define "areifounS" do |controller|
    controller.vm.box = "generic/alpine312"
    controller.vm.hostname = "areifounS"
    controller.vm.network "private_network", ip: "192.168.56.110"

    controller.vm.synced_folder ".", "/vagrant"

    controller.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    controller.vm.provision "shell", inline: <<-SHELL
    
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="" K3S_KUBECONFIG_MODE="644" sh -s - \
      --node-ip=192.168.56.110 \
      --advertise-address=192.168.56.110

      echo "[+] Waiting for K3s node-token..."
      until [ -f /var/lib/rancher/k3s/server/node-token ]; do
        sleep 3
      done

      echo "[+] NODE TOKEN"
      sudo mkdir -p /vagrant/k3s
      sudo sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/k3s/token
      echo "[+] DONE !"

    SHELL
  end

  # ----------------------
  # K3s Worker VM
  # ----------------------
  config.vm.define "areifounSW" do |agent|
    agent.vm.box = "generic/alpine312"
    agent.vm.hostname = "areifounSW"
    agent.vm.network "private_network", ip: "192.168.56.111"

    agent.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    agent.vm.synced_folder ".", "/vagrant"

    agent.vm.provision "shell", inline: <<-SHELL

      TOKEN=$(sudo cat /vagrant/k3s/token)

      curl -sfL https://get.k3s.io | \
        INSTALL_K3S_EXEC="--node-ip=192.168.56.111" \
        K3S_URL=https://192.168.56.110:6443 \
        K3S_TOKEN=$TOKEN \
        sh -

    SHELL
  end

end
