Vagrant.configure("2") do |config|

  # ----------------------
  # K3s Server VM
  # ----------------------
  config.vm.define "areifounS" do |controller|
    controller.vm.box = "ubuntu/focal64"
    controller.vm.hostname = "areifounS"
    controller.vm.network "private_network", ip: "192.168.56.110"

    controller.vm.synced_folder ".", "/vagrant", disabled: false

    controller.vm.provider "virtualbox" do |vb|
      vb.memory = 2024
      vb.cpus = 1
    end

    controller.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -s - \
        --node-ip=192.168.56.110 \
        --advertise-address=192.168.56.110

      sudo mkdir -p /vagrant/k3s
      sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/k3s/token
      #sudo chmod 644 /vagrant/k3s/token
    SHELL
  end

  # ----------------------
  # K3s Worker VM
  # ----------------------
  config.vm.define "areifounSW" do |agent|
    agent.vm.box = "debian/bullseye64"
    agent.vm.hostname = "areifounSW"
    agent.vm.network "private_network", ip: "192.168.56.111"

    agent.vm.provider "virtualbox" do |vb|
      vb.memory = 2024
      vb.cpus = 1
    end

    agent.vm.provision "shell", inline: <<-SHELL

      echo "Waiting for K3s token..."
      until [ -f /vagrant/k3s/token ]; do
        sleep 3
      done

      sudo apt-get update && sudo apt-get install -y curl

      TOKEN=$(cat /vagrant/k3s/token)

      curl -sfL https://get.k3s.io | \
        INSTALL_K3S_EXEC="--node-ip=192.168.56.111" \
        K3S_URL=https://192.168.56.110:6443 \
        K3S_TOKEN=$TOKEN \
        sh -

    SHELL
  end

end
